
const productCollection = [
  {
    id: "yqalbzikmm1",
    title: "leather-chair",
    price: 49.99,
    company: "ivins",
    img: "./images/product project/armchair.jpg",
  },
  {
    id: "tujkzmisxl2",
    title: "single-chair",
    price: 20.99,
    company: "fishy",
    img: "./images/product project/brombastic-chairs.jpg",
  },
  {
    id: "qollxziavs3",
    title: "boardroom-table",
    price: 75.55,
    company: "marcos",
    img: `./images/product project/center-table-chair.jpg`,
  },
  {
    id: "ppkdvmthzu4",
    title: "comfort relax-chair",
    price: 25.0,
    company: "seafood",
    img: `./images/product project/chair-confort.jpg`,
  },
  {
    id: "ryfkcvofmk5",
    title: "table and chair",
    price: 17.99,
    company: "fishy",
    img: `./images/product project/furniture-dining-table.jpg`,
  },
  {
    id: "euljxczaqq6",
    title: "ceramic-chair",
    price: 55.0,
    company: "marcos",
    img: `./images/product project/high-back-chair.jpg`,
  },
  {
    id: "ttsgbnudvu7",
    title: "livingroom-sofa",
    price: 120.0,
    company: "ivins",
    img: `./images/product project/indoor-sofa.jpg`,
  },
  {
    id: "uiaanbegxs8",
    title: "livingroom-chair",
    price: 49.99,
    company: "fishy",
    img: `./images/product project/keresi-room-chair.jpg`,
  },
  {
    id: "yedkvntjzp9",
    title: "kitchen cabinet",
    price: 300.99,
    company: "marcos",
    img: `./images/product project/kitchen-island-table.jpg`,
  },
  {
    id: "ewghmmulza10",
    title: "double chair-table",
    price: 50.99,
    company: "seafood",
    img: `./images/product project/lauduong-chair.jpg`,
  },
  {
    id: "oifjmnwhx11",
    title: "livingroom-high chair",
    price: 13.0,
    company: "fishy",
    img: `./images/product project/living-room-high-bench.jpg`,
  },
  {
    id: "tydfbvoscn12",
    title: "l-shape sofa",
    price: 280.99,
    company: "seasfood",
    img: `./images/product project/livingroom-sofa.jpg`,
  },
  {
    id: "pudovnrfcq13",
    title: "nursery-sofa",
    price: 15.0,
    company: "ivins",
    img: `./images/product project/nursery-sofa.jpg`,
  },
];